### ISSUE TITLE
Can ELFie be used on an ARM Cycle Model

### ISSUE THREAD

**Issue by imgod2u** [intel/pinball2elf#5]
I was wondering how ELFie's worked internally. Since they're standalone executables do they "warm up" the processor in the beginning to a known state using something other than register injection? If so, would that mean I can easily run these on an ARM cycle model?

**Comment by hgpatil** [comment]
ELFies as generated by the pinball2elf tool are x86-specific. That is because the incoming pinballs are x86-specific. The register injection is done at the beginning of each thread that ELFie creates and is based on the initial register state (x86-specific) as captured in the incoming pinball. The code that each thread created by ELFie will run is also x86-specific as it comes from the text pages captured in the incoming pinball.
To create ELFies that run on ARM, first you will need an ARM checkpoint generator and then pinball2elf will need to be re-targeted to convert that checkpoint format to an ELFie that will run on an ARM machine then.
